[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm install --production=false",
  "cd client && npm install --force",
  "cd client && npm install @tailwindcss/postcss --save-dev"
]

[phases.build]
cmds = [
  "cd client && npm run build"
]

[start]
cmd = "npm start"
