[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "npm ci --only=production --silent || npm install --silent",
  "cd client && npm ci --silent || npm install --silent"
]

[phases.build] 
cmds = [
  "cd client && npm run build"
]

[start]
cmd = "node server.js"
