[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm install --production=false",
  "cd client && npm install --force"
]

[phases.build]
cmds = [
  "cd client && npm run build --force"
]

[start]
cmd = "npm start"
